production:
  port: 9400
  pid_file: /var/www/coapcetic/shared/tmp/pids/searchd.pid
  indices_location: /var/www/coapcetic/shared/db/sphinx
  configuration_file: /var/www/coapcetic/shared/config/production.sphinx.conf
  binlog_path: /var/www/coapcetic/shared/binlog